services:
  database:
    image: postgres
    container_name: api-solid-pg
    ports:
      - 5432:5432

    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=api-solid

    volumes:
      - api-solid-pg:/var/lib/postgresql/data

volumes:
  api-solid-pg:
    name: api-solid-pg
